/* Bar functionality */
#include "bar_indicators.c"
#include "bar_tagicons.c"
#include "bar.c"

#include "bar_dwmblocks.c"
#include "bar_ltsymbol.c"
#include "bar_status.c"
#include "bar_status2d.c"
#include "bar_statuscmd.c"
#include "bar_winicon.c"
#include "bar_tagpreview.c"
#include "bar_tags.c"
#include "bar_wintitle.c"
#include "bar_fancybar.c"
#include "bar_awesomebar.c"
#include "bar_systray.c"
#include "bar_wintitleactions.c"

/* Other patches */
#include "attachx.c"
#include "exresize.c"
#include "fullscreen.c"
#include "movestack.c"
#include "pertag.c"
#include "placemouse.c"
#include "push.c"
#include "restartsig.c"
#include "scratchpad.c"
#include "shift.c"
#include "shiftviewclients.c"
#include "stacker.c"
#include "sticky.c"
#include "swallow.c"
#include "togglefullscreen.c"
#include "vanitygaps.c"
#include "warp.c"
#include "xrdb.c"
/* Layouts */
#include "layout_facts.c"
#include "layout_monocle.c"
#include "layout_tile.c"

